//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork_2_8_Client.ServiceReferenceASMX {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int User_idField;
        
        private int Id_departmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        private double SalaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int User_id {
            get {
                return this.User_idField;
            }
            set {
                if ((this.User_idField.Equals(value) != true)) {
                    this.User_idField = value;
                    this.RaisePropertyChanged("User_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Id_department {
            get {
                return this.Id_departmentField;
            }
            set {
                if ((this.Id_departmentField.Equals(value) != true)) {
                    this.Id_departmentField = value;
                    this.RaisePropertyChanged("Id_department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthdayField, value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Department_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameDepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Department_id {
            get {
                return this.Department_idField;
            }
            set {
                if ((this.Department_idField.Equals(value) != true)) {
                    this.Department_idField = value;
                    this.RaisePropertyChanged("Department_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameDepartment {
            get {
                return this.NameDepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.NameDepartmentField, value) != true)) {
                    this.NameDepartmentField = value;
                    this.RaisePropertyChanged("NameDepartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceASMX.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GetEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesResponse GetEmployees(HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesResponse> GetEmployeesAsync(HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name GetDepartmentResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartment", ReplyAction="*")]
        HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentResponse GetDepartment(HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentResponse> GetDepartmentAsync(HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployees", Namespace="http://tempuri.org/", Order=0)]
        public HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesRequestBody Body;
        
        public GetEmployeesRequest() {
        }
        
        public GetEmployeesRequest(HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdDepartment;
        
        public GetEmployeesRequestBody() {
        }
        
        public GetEmployeesRequestBody(int IdDepartment) {
            this.IdDepartment = IdDepartment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesResponseBody Body;
        
        public GetEmployeesResponse() {
        }
        
        public GetEmployeesResponse(HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HomeWork_2_8_Client.ServiceReferenceASMX.Employee[] GetEmployeesResult;
        
        public GetEmployeesResponseBody() {
        }
        
        public GetEmployeesResponseBody(HomeWork_2_8_Client.ServiceReferenceASMX.Employee[] GetEmployeesResult) {
            this.GetEmployeesResult = GetEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartment", Namespace="http://tempuri.org/", Order=0)]
        public HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentRequestBody Body;
        
        public GetDepartmentRequest() {
        }
        
        public GetDepartmentRequest(HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDepartmentRequestBody {
        
        public GetDepartmentRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentResponseBody Body;
        
        public GetDepartmentResponse() {
        }
        
        public GetDepartmentResponse(HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDepartmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HomeWork_2_8_Client.ServiceReferenceASMX.Department[] GetDepartmentResult;
        
        public GetDepartmentResponseBody() {
        }
        
        public GetDepartmentResponseBody(HomeWork_2_8_Client.ServiceReferenceASMX.Department[] GetDepartmentResult) {
            this.GetDepartmentResult = GetDepartmentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : HomeWork_2_8_Client.ServiceReferenceASMX.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<HomeWork_2_8_Client.ServiceReferenceASMX.WebService1Soap>, HomeWork_2_8_Client.ServiceReferenceASMX.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesResponse HomeWork_2_8_Client.ServiceReferenceASMX.WebService1Soap.GetEmployees(HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesRequest request) {
            return base.Channel.GetEmployees(request);
        }
        
        public HomeWork_2_8_Client.ServiceReferenceASMX.Employee[] GetEmployees(int IdDepartment) {
            HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesRequest inValue = new HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesRequest();
            inValue.Body = new HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesRequestBody();
            inValue.Body.IdDepartment = IdDepartment;
            HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesResponse retVal = ((HomeWork_2_8_Client.ServiceReferenceASMX.WebService1Soap)(this)).GetEmployees(inValue);
            return retVal.Body.GetEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesResponse> HomeWork_2_8_Client.ServiceReferenceASMX.WebService1Soap.GetEmployeesAsync(HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesRequest request) {
            return base.Channel.GetEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesResponse> GetEmployeesAsync(int IdDepartment) {
            HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesRequest inValue = new HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesRequest();
            inValue.Body = new HomeWork_2_8_Client.ServiceReferenceASMX.GetEmployeesRequestBody();
            inValue.Body.IdDepartment = IdDepartment;
            return ((HomeWork_2_8_Client.ServiceReferenceASMX.WebService1Soap)(this)).GetEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentResponse HomeWork_2_8_Client.ServiceReferenceASMX.WebService1Soap.GetDepartment(HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentRequest request) {
            return base.Channel.GetDepartment(request);
        }
        
        public HomeWork_2_8_Client.ServiceReferenceASMX.Department[] GetDepartment() {
            HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentRequest inValue = new HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentRequest();
            inValue.Body = new HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentRequestBody();
            HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentResponse retVal = ((HomeWork_2_8_Client.ServiceReferenceASMX.WebService1Soap)(this)).GetDepartment(inValue);
            return retVal.Body.GetDepartmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentResponse> HomeWork_2_8_Client.ServiceReferenceASMX.WebService1Soap.GetDepartmentAsync(HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentRequest request) {
            return base.Channel.GetDepartmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentResponse> GetDepartmentAsync() {
            HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentRequest inValue = new HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentRequest();
            inValue.Body = new HomeWork_2_8_Client.ServiceReferenceASMX.GetDepartmentRequestBody();
            return ((HomeWork_2_8_Client.ServiceReferenceASMX.WebService1Soap)(this)).GetDepartmentAsync(inValue);
        }
    }
}
